### ISSUE TITLE
org clock support

### ISSUE THREAD

**Issue by d12frosted** [Malabarba/smart-mode-line#137]
Hey, I am using org clock feature and when I do `org-clock-in` it adds some information to mode line (like duration and item). It adds it at the very right. And when I use `smart-mode-line` this additional info is far too away on right side of mode line. So actually I see only part of this info.

![screenshot 2015-06-03 16 33 46](https://cloud.githubusercontent.com/assets/6507913/7961204/9c8b4b74-0a0e-11e5-97de-4fbf241ec426.png)

My first thought was that there are some problems with my mode width. But `sml/mode-width` is set to `full` and `sml/name-width` is set to `44`. Am I missing something?

**Comment by Malabarba** [comment]
Hi there, I don't think you're missing anything. The `'full` configuration for `sml/modes-width` can be a little shaky on some corner cases. When some mode adds unusual information to the mode-line is one of these cases.
It can also fail if the theme you're using changes the size of the mode-line face.

I think the best you can do here is set `sml/modes-width` to a number instead of `'full`.

**Comment by Mitchicus** [comment]
I have had a similar issue with the regular time on mode line function being forced very far right. Through some tinkering of the numbers (in my personal case with sml powerline), setting name width = 20 and mode width = 10 fixed everything.

**Comment by d12frosted** [comment]
Thank you for comments. Setting `sml/mode-width` helped. Was tuning only `sml/name-width`.
