### ISSUE TITLE
Question: Is in possible Turn SML off per major mode

### ISSUE THREAD

**Issue by mikef656** [Malabarba/smart-mode-line#143]
Probably a in a hook.
Something like:

(add-hook 'some-mode-hook
   (lambda ()
   (smart-mode-line-mode 0))

or

(add-hook 'some-mode-hook
   (lambda ()
   (sml/do-not-modify-mode-line-this-major-mode))

**Comment by Malabarba** [comment]
Sadly, no. Sml just changes the default value of all the mode-line variables, which makes it global.
Technically it could just set the local value on each buffer, but that would likely come with a performance hit.
Is there any reason why you don't want sml on a specific mode?

**Comment by Mike--F** [comment]
Sunrise-commander is a dual pane file manager derived from dired.  Normally it's mode line contains the path to the pwd.  The user can click on any part of the path, then the file manager changes directory to that part of the path that was clicked on;nice.  Sml interacts with it in some ways that are undesired.

I have a short defun that splits a single window vertically and shows a narrowed dired buffer in the left half.  It's mode line shows just the name of the current folder, rather than the entire folder path (which is what sml does and I like for buffers associated with files)

Would like to simply turn off sml in these two major modes: sr-mode, dired-mode.

**Comment by Malabarba** [comment]
You should be able to get what you want by locally changing the value of `mode-line-buffer-identification` in those modes. For instance, here's what you can do for dired:

    (defun my-dired-mode-line ()
      (setq mode-line-buffer-identification '("%17b")))
    (add-hook ' dired-mode-hook #'my-dired-mode-line 'append)

Or, if you want to make the mode-line even cleaner, you can do:
    (defun my-dired-mode-line ()
      (setq mode-line-format '("%17b")))

For sunrise you will need something similar.
