### ISSUE TITLE
How Can I Display time in the middle ?

### ISSUE THREAD

**Issue by MalcolmChen** [Malabarba/smart-mode-line#197]
I'm Using org-mode, and i got a counting down timer. now it's displayed in the right corner of mode line. i wanna it displayed in the middle, any tips?
if i turn on the time display with display-time-mode, this timer displayed with time, how can i split them up -- which i mean display the count down timer in the middle and time in the right.

**Comment by sten0** [comment]
I'm not sure centering the org-mode countdown timer would be practical, because that's where minor modes usually end up.  As a compromise I'd suggest putting it somewhere around `sml/pos-id-separator` or `sml/pre-modes-separator`.  The one caveat is that might be a no-go if that countdown timer hacks into `display-time-string`...if it does this then org-mode would first need to gain the ability to split countdown-timer from `time-string`.

**Comment by Malabarba** [comment]
Closing this as it's not sml-specific. Feel free to ask for help on emacs.stackexchange about stuff like this.
